const express = require('express')
const { authRouter } = require('./auth')
const { categoriesRouter } = require('./categories')
const { ingredientsRouter } = require('./ingredients')
const { originsRouter } = require('./origins')
const { preparationsRouter } = require('./preparations')
const { preparationItemsRouter } = require('./preparationItems')
const { unitConversionsRouter } = require('./unitConversions')
const { purchasesRouter } = require('./purchases')
const { purchaseItemsRouter } = require('./purchaseItems')
const { transfersRouter } = require('./transfers')
const { transferItemsRouter } = require('./transferItems')
const { runningStockRouter } = require('./runningStock')
const { stockTransitionsRouter } = require('./stockTransitionStates')

const router = express.Router()

router.use('/auth', authRouter)
router.use('/categories', categoriesRouter)
router.use('/ingredients', ingredientsRouter)
router.use('/origins', originsRouter)
router.use('/preparations', preparationsRouter)
router.use('/preparation-items', preparationItemsRouter)
router.use('/unit-conversions', unitConversionsRouter)
router.use('/purchases', purchasesRouter)
router.use('/purchase-items', purchaseItemsRouter)
router.use('/transfers', transfersRouter)
router.use('/transfer-items', transferItemsRouter)
router.use('/running-stock', runningStockRouter)
router.use('/stock-transitions', stockTransitionsRouter)

module.exports = { v1Router: router }
