const express = require('express')
const { authRouter } = require('./auth')
const { categoriesRouter } = require('./categories')
const { ingredientsRouter } = require('./ingredients')
const { originsRouter } = require('./origins')
const { preparationsRouter } = require('./preparations')
const { preparationItemsRouter } = require('./preparationItems')
const { unitConversionsRouter } = require('./unitConversions')
const { purchasesRouter } = require('./purchases')
const { purchaseItemsRouter } = require('./purchaseItems')
const { transfersRouter } = require('./transfers')
const { transferItemsRouter } = require('./transferItems')
const { utilizationsRouter } = require('./utilizations')
const { utilizationItemsRouter } = require('./utilizationItems')
const { runningStockRouter } = require('./runningStock')
const { runningStockConfigurationRouter } = require('./runningStockConfiguration')
const { stockTransitionsRouter } = require('./stockTransitionStates')
const { stocksRouter } = require('./stocks')
const { reportsRouter } = require('./reports')

const router = express.Router()

router.use('/auth', authRouter)
router.use('/categories', categoriesRouter)
router.use('/ingredients', ingredientsRouter)
router.use('/origins', originsRouter)
router.use('/preparations', preparationsRouter)
router.use('/preparation-items', preparationItemsRouter)
router.use('/unit-conversions', unitConversionsRouter)
router.use('/purchases', purchasesRouter)
router.use('/purchase-items', purchaseItemsRouter)
router.use('/transfers', transfersRouter)
router.use('/transfer-items', transferItemsRouter)
router.use('/utilizations', utilizationsRouter)
router.use('/utilization-items', utilizationItemsRouter)
router.use('/running-stock/configuration', runningStockConfigurationRouter)
router.use('/running-stock', runningStockRouter)
router.use('/stock-transitions', stockTransitionsRouter)
router.use('/stocks', stocksRouter)
router.use('/reports', reportsRouter)

module.exports = { v1Router: router }
